### ISSUE TITLE
Feedback from the website users

### ISSUE THREAD

**Issue by alperkan1** [alperkan1/user-stories#1]
In order to **get insightful feedback** as a **website user**, I can **i would like to see the usage of a poll**

**Comment by alperkan1** [comment]
**Acceptance Criteria **
 
 1. Create a pool using 4 options with buttons.
 2. Get the user to give opinion as a check box poll.
 3. The user has to chose one to submit.
 4. Have a text box for any feedback

**Comment by alperkan1** [comment]
**TASKS:**
- [x] update the html and create a new page jut for the poll and feedback
- [x] use the old footer and header on the site 
- [x] create a multi option check box with must check questions in total 4 questions
- [ ] create a text box for the input if user wants additional questions
- [ ] create that when submitted it puts data on to a excel cvv file and e mails the feed back also to administrator
